---
title: "Figures for Reproducible Research"
author: 
  - Fabio Cruz 
  - Giovanny Arbelaez
  - Mauricio
date: "24/01/202"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(yaml)
library(markdown)

```




## Goal

The main goal of this template is to explore first a data visualization.
- Explore the diferents possibilities that `ggplot2` package could give.


## Initial configuration

Create a new `.Rmd` documents using a the following `YAML` configuration, changing the names.

```yaml
---
title: "GGPL2 Reproducible Document"
date: "May 1, 2015"
author:
  - Student 1
  - Student 2
  - Student 3
output: html_document
---
```

Create a configuration chunk:

````markdown
`r ''````{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```
````
***

## Introduction

**ggplot2** is a powerful and a flexible R package, implemented by Hadley Wickham, for producing elegant graphics.

The concept behind ggplot2 divides plot into three different fundamental parts: *Plot = data + Aesthetics + Geometry**.

The principal components of every plot can be defined as follow:

- **data** is a data frame
- **Aesthetics** is used to indicate x and y variables. It can also be used to control the **color**, the size or the shape of points, the height of bars, etc…..
- Geometry defines the type of graphics (histogram, box plot, line plot, density plot, dot plot, ….)

There are two major functions in ggplot2 package: **qplot()** and **ggplot()** functions.

**qplot()** stands for quick plot, which can be used to produce easily simple plots.

**ggplot()** function is more flexible and robust than qplot for building a plot piece by piece.


# Thing to do for ARCHE

*Follow the proposed tutorials using your own *:

## About R
- [R (English)](http://r-statistics.co/R-Tutorial.html)
- [R (In french)](https://larmarange.github.io/analyse-R/premier-contact.html)


  - Basesd on these tutorials on R, Go to the Assigment 1




## About `ggplot2`
- [ggplot2 Short Tutorial](http://r-statistics.co/ggplot2-Tutorial-With-R.html)
- [ggplot2 Tutorial 1 - Intro](http://r-statistics.co/Complete-Ggplot2-Tutorial-Part1-With-R-Code.html)
- [ggplot2 Tutorial 2 - Theme](http://r-statistics.co/Complete-Ggplot2-Tutorial-Part2-Customizing-Theme-With-R-Code.html)


*Make an html document presenting based on the tutorials: *
- 




